### ISSUE TITLE
Return 400 error

### ISSUE THREAD

**Issue by AlessioAgnese** [ozkc/instagram-unfollowers#4]
I dont use 2 Factory Auth, when I try to run the script it cant log in saying request return error 400 and login failed, the instagram app on my smartphone alert a suspect access, there is a way to make work? :) 
Using python2.7 on Ubunto 19.10 && Private Instagram account

**Comment by ccozkan** [comment]
I see. If you havent tried, you can try approve the login on the app or browser, also try to login to instagram in browser an run the script in your local computer(since it has same geolocation as your phone). 

But as a workaround, you can create another account (a throwaway account) and enter its credentials, follow the account (the one you'll need its instagram id)  since it's private and then run the script.

**Comment by AlessioAgnese** [comment]
Solved, now works, thanks for your advice man :)
